### ISSUE TITLE
Not working with ZSH History

### ISSUE THREAD

**Issue by domsch1988** [crclark96/ginh#4]
Great Script! It doesn't work with ZSH History files though, as they are formated differently. The following should work:
calc=$(cat $histfile | sed s/sudo//g | awk -F ';' '{print $2}' | awk '{print $1}' | sort | uniq -c | sort -rn)
I also included a sed command to strip sudo out, as all sudo commands are counted the same. But that's just, because i'm more interested in what i actually did with sudo. One could output two graphs, one for Sudo commands and one without.

Maybe the current shell can be recieved programatically with "echo $0" and handle the histfile and calculation depending on what's returned.

**Comment by crclark96** [comment]
I didn't think about stripping `sudo`, that's a great idea.

As for detecting the shell and automatically adjusting the format, @theryangeary has been taking a look at the best way to do this. Unfortunately, `echo $0` resolves to the current shell, which will always be `/bin/bash` in this script, because of the interpreter specified at the top.

I promise you'll be the first to know when we figure out how to manage multiple shells completely automatically. Thanks for the new `calc` line for when we do!

**Comment by theryangeary** [comment]
`echo $0` actually returns the name of the executable, in this case `ginh.sh`. What we really want is the name of the parent process, which we can easily check against the list of shells that people use. The bigger issue is that I don't believe that all history files are formatted in the same way and I'm having trouble finding references for the different possible formats, zsh or otherwise.

**Comment by theryangeary** [comment]
`ps -o comm=$PPID | grep ps -B 1 | head -1` seems to reliably report the shell that was used to call the script.

**Comment by crclark96** [comment]
Right, `$n` are the `argv` in bash. 

I'm wondering if there's an easy way to export the `$SHELL` and `$HISTFILE` using `env` when we invoke the script that doesn't require special interaction from the user:

> The env utility executes another utility after modifying the environment as
>     specified on the command line.  Each name=value option specifies the set-
>     ting of an environment variable, name, with a value of value.  All such
>     environment variables are set before the utility is executed.

It'd be easy enough to use the variables if `ginh.sh` is invoked through `env`.

Food for thought

**Comment by rashivkp** [comment]
This is what I get. 
```
[2]  + 27930 suspended (tty input)  ./ginh.sh
```

Using zsh

**Comment by crclark96** [comment]
#5 fixes this issue.

@rashivkp, your output looks like the script is being pushed into the background, which would be a separate issue from this one. Could you please open a new issue and include details about how it's being launched and any other information that would be helpful? We'll try to debug in that separate thread.

Thanks for the issue @domsch1988, glad we spent time looking into this. And thanks for the fix @theryangeary!
